/********************************************************************
* qcdEstimationDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error qcdEstimationDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableqcdEstimationDict();
extern void G__cpp_setup_inheritanceqcdEstimationDict();
extern void G__cpp_setup_typetableqcdEstimationDict();
extern void G__cpp_setup_memvarqcdEstimationDict();
extern void G__cpp_setup_globalqcdEstimationDict();
extern void G__cpp_setup_memfuncqcdEstimationDict();
extern void G__cpp_setup_funcqcdEstimationDict();
extern void G__set_cpp_environmentqcdEstimationDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AbcdBase.h"
#include "DataSample.h"
#include "DoABCD.h"
#include "ABCDReader.h"
#include "DoRSMT.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__qcdEstimationDictLN_TClass;
extern G__linked_taginfo G__qcdEstimationDictLN_TBuffer;
extern G__linked_taginfo G__qcdEstimationDictLN_TMemberInspector;
extern G__linked_taginfo G__qcdEstimationDictLN_TString;
extern G__linked_taginfo G__qcdEstimationDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_string;
extern G__linked_taginfo G__qcdEstimationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__qcdEstimationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__qcdEstimationDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__qcdEstimationDictLN_TFile;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBase;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBasecLcLEModeType;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBasecLcLRegionEnum;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBasecLcLETableFormat;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBasecLcLEErrorFormat;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBasecLcLDimensionEnum;
extern G__linked_taginfo G__qcdEstimationDictLN_AbcdBasecLcLSampleEnum;
extern G__linked_taginfo G__qcdEstimationDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__qcdEstimationDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__qcdEstimationDictLN_DataSample;
extern G__linked_taginfo G__qcdEstimationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__qcdEstimationDictLN_maplETStringcOTH1DmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTH1DmUgRsPgRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_ABCDReader;
extern G__linked_taginfo G__qcdEstimationDictLN_maplETStringcOABCDReadermUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOABCDReadermUgRsPgRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_DoABCD;
extern G__linked_taginfo G__qcdEstimationDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__qcdEstimationDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__qcdEstimationDictLN_DoRSMT;

/* STUB derived class for protected member access */
